services:
  - type: web
    name: liontechweb
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
    startCommand: gunicorn liontechweb.asgi:application --bind 0.0.0.0:$PORT -k uvicorn.workers.UvicornWorker
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: 'False'
        sync: false
      - key: ALLOWED_HOSTS
        value: '0.0.0.0,127.0.0.1'
        sync: false
    staticPublishPath: static
