# Generated by Django 5.2.4 on 2025-08-11 09:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(default=0)),
                ('name', models.CharField(default='Unknown Product', max_length=255)),
                ('image', models.URLField(blank=True, default='', max_length=500, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('category', models.CharField(default='Uncategorized', max_length=100)),
                ('condition', models.CharField(default='N/A', max_length=50)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='products/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Mobiles & Accessories', 'Mobiles & Accessories'), ('TVs', 'TVs'), ('Cameras & Accessories', 'Cameras & Accessories')], max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('brand_model', models.CharField(default='Unknown', max_length=255)),
                ('color', models.CharField(default='Black', max_length=50)),
                ('storage_ram', models.CharField(default='64GB/4GB', max_length=50)),
                ('network', models.CharField(default='4G LTE', max_length=100)),
                ('battery', models.CharField(default='4000mAh', max_length=100)),
                ('camera', models.CharField(default='12MP Rear / 8MP Front', max_length=100)),
                ('screen', models.CharField(default='6.5” LCD', max_length=100)),
                ('processor', models.CharField(default='Snapdragon 680', max_length=100)),
                ('os', models.CharField(default='Android 13', max_length=100)),
                ('accessories', models.CharField(default='Charger, USB Cable', max_length=255)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Used', 'Used'), ('Refurbished', 'Refurbished')], default='New', max_length=50)),
                ('warranty', models.CharField(default='No Warranty', max_length=100)),
                ('optional_details', models.TextField(blank=True, default='N/A')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.product')),
            ],
        ),
    ]
