# Generated by Django 5.2.4 on 2025-08-11 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cartOrder',
        ),
    ]
