# Generated by Django 5.2.4 on 2025-08-11 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_cartorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
