# Generated by Django 5.2.6 on 2025-09-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Location',
            field=models.CharField(default='Local', max_length=100),
        ),
    ]
