# Generated by Django 5.2.6 on 2025-09-05 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_product_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Location',
            new_name='location',
        ),
    ]
