# Generated by Django 5.2.6 on 2025-09-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_bundle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='category',
        ),
        migrations.RemoveField(
            model_name='bundle',
            name='published',
        ),
        migrations.RemoveField(
            model_name='bundle',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='bundle',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='bundles/'),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='image',
            field=models.ImageField(default=1, upload_to='bundles/'),
            preserve_default=False,
        ),
    ]
