# Generated by Django 5.2.6 on 2025-09-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_remove_bundle_category_remove_bundle_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='image_desc_1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='bundle',
            name='image_desc_2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
