# Generated by Django 5.2.6 on 2025-09-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_bundle_image_desc_1_bundle_image_desc_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
