# Generated by Django 5.2.6 on 2025-09-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_order_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='bundles', to='website.product'),
        ),
    ]
