# Generated by Django 5.2.6 on 2025-09-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_bundle_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bundles/'),
        ),
    ]
